name:                Exckel
version:             0.0.1.0
github:              "sheepforce/Exckel"
license:             GPL-3
author:              "Phillip Seeber"
maintainer:          "phillip.seeber@uni-jena.de"
copyright:           "2019 Phillip Seeber"

extra-source-files:
  - README.md
  - LICENSE
  - data/Exckel.txt
  - data/VMD.tcl

data-dir: data

data-files:
  - Exckel.txt
  - VMD.tcl


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/Exckel#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - microlens-platform >= 0.3.11
    - text >= 1.2.3.1
    - attoparsec >= 0.13.2.2
    - vector >= 0.12.0.2
    - pandoc >= 2.5
    - pandoc-types >= 1.17.5.4
    - bytestring >= 0.10.8.2
    - process >= 1.6.3.0
    - directory >= 1.3.3.0
    - ginger >= 0.8.4.0
    - mtl >= 2.2.2
    - filepath >= 1.4.2.1
    - unordered-containers >= 0.2.9.0
    - cmdargs >= 0.10.20
    - file-embed >= 0.0.11
  default-extensions:
    - OverloadedStrings

executables:
  Exckel-exe:
    main: Exckel.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Exckel
      - cmdargs >= 0.10.20
      - microlens-platform >= 0.3.11
      - directory >= 1.3.3.0
      - text >= 1.2.3.1
      - attoparsec >= 0.13.2.2
      - filepath >= 1.4.2.1
      - pandoc >= 2.5
      - bytestring >= 0.10.8.2
      - ansi-terminal >= 0.8.2
